# This is a basic workflow to help you get started with Actions
name: Vercel Deployment

on:
  push:
    branches: 
      - main
      - prod
    paths-ignore:
      - "**/README.md"
  pull_request:
    branches: 
      - main
      - prod
    paths-ignore:
      - "**/README.md"
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build_test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [ 16.x ]

    steps:
      - uses: actions/checkout@v3

      - name: setup node
        uses: actions/setup-node@master
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: |
          npm i pnpm -g
          pnpm i
      - name: Prepare
        run: |
          pnpm run img:process
      - name: Lint
        run: |
          pnpm run lint
          pnpm run stylelint
      - name: build
        run: |
          pnpm run build

  push_to_vercel:

    needs: build_test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: amondnet/vercel-action@v25
        if: github.event_name == 'push' && github.ref == 'refs/heads/prod'
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID}}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID}}
          vercel-args: "--prod"
