name: build-and-deploy
on:
  push:
    paths-ignore:
      - "**.md"
  pull_request:
    paths-ignore:
      - "**.md"
jobs:
  disable:
    if: false
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Install and build
        run: |
          npm install
          npm run build
      - name: Upload Artifacts
        uses: actions/upload-artifact@v1
        with:
          name: project
          path: build
  deploy:
    needs: [build]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.1
      - name: Download Artifacts
        uses: actions/download-artifact@v1
        with:
          name: project 
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: project
          clean: true
          clean-exclude: |
            .nojekyll
            CNAME
